### ISSUE TITLE
Error 500 when activating JS minify from latest update

### ISSUE THREAD

**Issue by jacobd91** [BoldGrid/w3-total-cache#418]
Related to #392

**Comment by jacobd91** [comment]
Wordpress.org reference post https://wordpress.org/support/topic/error-500-when-activating-js-minify-from-latest-update/

**Comment by jacobd91** [comment]
<img width="797" alt="errors" src="https://user-images.githubusercontent.com/88040916/132029929-83a69871-3b2b-4161-a09a-1f686f680b3d.png">

**Comment by mavas84** [comment]
@jacobd91 I've asked the user to contact us directly.
Waiting for the feedback.

**Comment by He-Man321** [comment]
Hello, it's me again!

So, to recap...

Initially, when we enabled minification of JS it failed and caused an HTTP 500 error in the console when loading the minified .JS files.  As a fix I went to:
C:\inetpub\Site1\wp-content\plugins\w3-total-cache\lib\Minify\JSMin.php
and edited line 210 to read:
if ($this->a === "'" || $this->a === '"') { // string literal
And the problem went away.  Turning off minification of JS also fixes it.

This is a Windows server, so the caching is just Disk\Disk Advanced.

I assume the PHP that minifies the JS is failing, possibly due to an odd character, so when the browser tries to fetch it, the HTTP 500 is from the failing PHP.

If I try and enable the minify debug option I get “It appears Minify URL rewriting is not working. Please verify that the server configuration allows .htaccess” but as I am running on Windows there is no .htaccess file (or at least, not one that does anything) and it has not created and IIS rewrite rules in the web.config.

Could we just log $this->a somewhere and see what it is working on?  How would I go about doing this?

**Comment by He-Man321** [comment]
Hello guys, any news on this? Can you advise on how I can go about diagnosing the issue?
