### ISSUE TITLE
Disable OpCache purge all after every post update.

### ISSUE THREAD

**Issue by mavas84** [BoldGrid/w3-total-cache#594]
OPcache is flushed every time when a post/article is published or a page is updated, an unnecessary action that may have a significant impact on performance.
Prevent OpCache flush all after every update, and add the ability to only manually purge OpCache.
Reference topic: https://wordpress.org/support/topic/disable-opcache-within-w3tc/

**Comment by maxicus** [comment]
@mavas84 I can confirm it's not purged on every post update.
More than that - it's never called by implicit actions like changing something somewhere.

The only way to purge opcache cache is to issue "Flush All" operation. By UI button or programatically.
What's seems correct behavior since it says flush *all* we know we can flush.

That means environment claiming it calling `w3tc_flush_all` by itself (potentially some plugin).
