### ISSUE TITLE
Custom selected page not purged due slash

### ISSUE THREAD

**Issue by mikaelz** [BoldGrid/w3-total-cache#647]
Tested version: 2.2.12

`Util_PageUrls::get_pages_urls( $pages )` returns `['http://localhost:8000/magazin/']` even when `$this->_config->get_array( 'pgcache.purge.pages' )` returns `magazin` without slash at the end.

`_flush_url()` removes `localhost:8000/_index_slash.html` and not `localhost:8000/_index.html`

Workaround fix is 
```
// Fix w3tc selected page purge
add_filter('w3tc_pagecache_flush_url_keys', 'moda_w3tc_pagecache_flush_url_keys');
function moda_w3tc_pagecache_flush_url_keys($page_keys) {
	$new_page_keys = [];
	foreach ( $page_keys as $page_key ) {
		$new_page_keys[] = $page_key;
		$new_page_keys[] = str_replace( '_slash','', $page_key );
	}

	return $new_page_keys;
}
```

**Comment by mavas84** [comment]
Hello @mikaelz 

Thank you for reaching out and for taking the time to share your findings.
We, however, were not able to replicate this even with forcing PageCache to generate the _index.html file, it successfully flushes both the _index.html and  _index_slash.html files.
In order to see if there are some potential misconfigurations, can you please share your configuration by exporting the JSON file in Performance>General Settings>Import/Export Settings, or the wp-config/w3tc-config/master.php file?
Please share this via the W3 Total Cache support channel in Performance>Support to avoid sharing any sensitive information

Thanks!

**Comment by mavas84** [comment]
No feedback
