### ISSUE TITLE
cache-control policy being shown twice!

### ISSUE THREAD

**Issue by MediaMaquina** [BoldGrid/w3-total-cache#650]
HTML cache-control shows up like so:
`cache-control: max-age=604768, public, must-revalidate, proxy-revalidate, public, must-revalidate, proxy-revalidate`
it should be just:
`cache-control: max-age=604768, public, must-revalidate, proxy-revalidate`
![2](https://user-images.githubusercontent.com/8179611/218989500-bd538ecc-9fff-448b-a3a9-e4d24ef19d71.png)

![1](https://user-images.githubusercontent.com/8179611/218989175-152e9850-8bd8-4492-afc5-aa44bfffce05.png)

Also as a note: I must deactivate and reactivate the plugin for the policies to take effect, don't know why.

**Comment by mavas84** [comment]
Hello @MediaMaquina 

Thank you for reaching out. 
I am unable to replicate this issue so I need more information about this.
Since this is mostly a support question, please reach out to us directly via the plugin in Performance>Support or via the [website contact form](https://www.w3-edge.com/contact/), and share the website URL and other information that you may not want to share here in the public repo.
Thanks!

**Comment by MediaMaquina** [comment]
Ok must be on my end then. ty-
