### ISSUE TITLE
Don't blindly add "define('WP_CACHE', true)" to wp-config.php

### ISSUE THREAD

**Issue by jamieburchell** [BoldGrid/w3-total-cache#752]
Please check if the `WP_CACHE` constant is already defined before defining it in `wp-config.php` file.

In my development environment, this constant is already set to `false` to disable caching. When for example viewing the plugins page in the admin, W3TC adds `define('WP_CACHE', true)` to the `wp-config.php` causing a fatal error on the next page view:

```
Fatal error: Uncaught Roots\WPConfig\Exceptions\ConstantAlreadyDefinedException: Aborted trying to redefine constant 'WP_CACHE'. `define('WP_CACHE', ...)` has already been occurred elsewhere. in /web/vendor/roots/wp-config/src/Config.php on line 106
```

**Comment by cssjoe** [comment]
@jamieburchell The `wp-config.php` file is loaded before the `Config.php` file, so a condition should be added in the `Config.php` file rather than in `wp-config.php`.  Alternatively, you can change the value of the definition in `wp-config.php`.
W3TC adds the define() call at https://github.com/BoldGrid/w3-total-cache/blob/2.6.1/PgCache_Environment.php#L377.  It's unclear if we would be able to detect if a definition is present elsewhere, as it depends on the loading order.

**Comment by jamieburchell** [comment]
@cssjoe Roots Bedrock [does check if the constant is defined](https://github.com/roots/wp-config/blob/a26c7d274b76397a99faa4e8d8d981b5536a24cb/src/Config.php#L105).

The issue seems to be that the value is also checked, so if I have set it to `false` in Bedrock and W3TC adds a define with `true` an exception is thrown.

**Comment by cssjoe** [comment]
Try to not set it (or comment it out) in Bedrock and change the value in `wp-config.php` to `false`.

**Comment by jamieburchell** [comment]
We don't use the wp-config.php for defining constants. In Bedrock this is handled elsewhere using environment specific config files. I guess it would just be better if we could stop W3TC from modifying the file at all. In production the file cannot be written to so it's not an issue but it always catches me out in development.
